version: "3"

services:

  node:
    image: node:16.14
    container_name: lexart_node
    build: ./ 
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - mongodb
    ports:
      - 3001:3001
    environment:
      - MONGO_URL=mongodb://mongodb:27017/lexartdb

  mongodb:
    image: mongo:5.0.7
    container_name: lexart_mongo
    volumes:
      - ./:/app
    restart: always
    ports:
      - 27017:27017

networks:
  default:
    name: lexart_net